### PR TITLE
Yes in ArnoldC

### PR DESCRIPTION
**Pull request by li223**
Created yes in ArnoldC

### CODE REVIEW

**Comment by RaidAndFade** [comment]
Your pull request seems good, but must be checked by a human maintainer for the following reason(s):
1. An error occured while marking your code. The error should be addressed by a maintainer eventually. The error is: ```File extension .arnoldc is not supported```.
2. These submissions must be checked manually because of the potential complexity of submissions, if you've reached this point in the process you're most likely a valid submission.

Please be patient until a maintainer has time to look over your contribution.

***This is an automated response, beep boop.
if you think there is a mistake, contact a maintainer***
> 468923f29043fc5e7979571818d9c8c29f9df334

**Comment by li223** [comment]
The code can be run on this site: http://mapmeld.com/ArnoldC/

**Comment by RaidAndFade** [comment]
Looks Good, Thanks!

**Comment by RaidAndFade** [comment]
😗 love u li join my server again you butt

**Pull request merged**
