### PR TITLE
Add Lisp

### PR DESCRIPTION
**Pull request by Erfaniaa**
#hacktoberfest

### CODE REVIEW

**Comment by RaidAndFade** [comment]
Your pull request seems good, but must be checked by a human maintainer for the following reason(s):
1. Modifications to contributors.md must be checked manually, thanks for your submission.
2. An error occured while marking your code. The error should be addressed by a maintainer eventually. The error is: ```File extension .lisp is not supported```.
3. These submissions must be checked manually because of the potential complexity of submissions, if you've reached this point in the process you're most likely a valid submission.

Please be patient until a maintainer has time to look over your contribution.

***This is an automated response, beep boop.
if you think there is a mistake, contact a maintainer***
> f8b41951448f28d31a4feb75c05831ca7d663136

**Comment by Erfaniaa** [comment]
#1 #2

**Comment by RaidAndFade** [comment]
This request's code has changed since approval. Re-Judging contents...
Your pull request seems good, but must be checked by a human maintainer for the following reason(s):
1. Modifications to contributors.md must be checked manually, thanks for your submission.
2. An error occured while marking your code. The error should be addressed by a maintainer eventually. The error is: ```File extension .lisp is not supported```.
3. These submissions must be checked manually because of the potential complexity of submissions, if you've reached this point in the process you're most likely a valid submission.

Please be patient until a maintainer has time to look over your contribution.

***This is an automated response, beep boop.
if you think there is a mistake, contact a maintainer***
> 4d450d43efca4f13a20540e25477bcf71be166da

**Comment by RaidAndFade** [comment]
Looks good, thanks

**Pull request merged**
