### PR TITLE
Yes in Powershell

### PR DESCRIPTION
**Pull request by Phyre1337**
Wrote yes in a powershell script.

### CODE REVIEW

**Comment by RaidAndFade** [comment]
Your pull request seems good, but must be checked by a human maintainer for the following reason(s):
1. Modifications to contributors.md must be checked manually, thanks for your submission.
2. An error occured while marking your code. The error should be addressed by a maintainer eventually. The error is: ```File extension .ps1 is not supported```.
3. These submissions must be checked manually because of the potential complexity of submissions, if you've reached this point in the process you're most likely a valid submission.

Please be patient until a maintainer has time to look over your contribution.

***This is an automated response, beep boop.
if you think there is a mistake, contact a maintainer***
> 880312661a6bb6aedde2bae4f6b15afb13ce766e

**Comment by Phyre1337** [comment]
Is there anymore conflicts now? @RaidAndFade

**Comment by RaidAndFade** [comment]
This request's code has changed since approval. Re-Judging contents...
Your pull request seems good, but must be checked by a human maintainer for the following reason(s):
1. Modifications to contributors.md must be checked manually, thanks for your submission.
2. An error occured while marking your code. The error should be addressed by a maintainer eventually. The error is: ```File extension .ps1 is not supported```.
3. These submissions must be checked manually because of the potential complexity of submissions, if you've reached this point in the process you're most likely a valid submission.

Please be patient until a maintainer has time to look over your contribution.

***This is an automated response, beep boop.
if you think there is a mistake, contact a maintainer***
> bd61d1c40df13a0e1ec7ec8b0eff1166359ac6eb

**Comment by RaidAndFade** [comment]
Looks Good, Thanks!

**Pull request merged**
