### PR TITLE
batch

### PR DESCRIPTION
**Pull request by keksbg**
* add batch

### CODE REVIEW

**Comment by RaidAndFade** [comment]
Your pull request seems good, but must be checked by a human maintainer for the following reason(s):
1. Modifications to contributors.md must be checked manually, thanks for your submission.
2. An error occured while marking your code. The error should be addressed by a maintainer eventually. The error is: ```File extension .bat is not supported```.
3. These submissions must be checked manually because of the potential complexity of submissions, if you've reached this point in the process you're most likely a valid submission.

Please be patient until a maintainer has time to look over your contribution.

***This is an automated response, beep boop.
if you think there is a mistake, contact a maintainer***
> 079eae5375946714fbd0c731ed0f67ce93b88425

**Review by y21 — APPROVED** [review]

**Comment by RaidAndFade** [comment]
This request's code has changed since approval. Re-Judging contents...
Your pull request seems good, but must be checked by a human maintainer for the following reason(s):
1. Modifications to contributors.md must be checked manually, thanks for your submission.
2. An error occured while marking your code. The error should be addressed by a maintainer eventually. The error is: ```File extension .bat is not supported```.
3. These submissions must be checked manually because of the potential complexity of submissions, if you've reached this point in the process you're most likely a valid submission.

Please be patient until a maintainer has time to look over your contribution.

***This is an automated response, beep boop.
if you think there is a mistake, contact a maintainer***
> 03d66f4f68aa877eaafa67472d9e7bcc1c7c3776

**Comment by RaidAndFade** [comment]
This request's code has changed since approval. Re-Judging contents...
Your pull request seems good, but must be checked by a human maintainer for the following reason(s):
1. Modifications to contributors.md must be checked manually, thanks for your submission.
2. An error occured while marking your code. The error should be addressed by a maintainer eventually. The error is: ```File extension .bat is not supported```.
3. These submissions must be checked manually because of the potential complexity of submissions, if you've reached this point in the process you're most likely a valid submission.

Please be patient until a maintainer has time to look over your contribution.

***This is an automated response, beep boop.
if you think there is a mistake, contact a maintainer***
> d053e5fe806e5c9ea21fd0edeb3d8eaced4030ba

**Comment by RaidAndFade** [comment]
This request's code has changed since approval. Re-Judging contents...
Your pull request seems good, but must be checked by a human maintainer for the following reason(s):
1. Modifications to contributors.md must be checked manually, thanks for your submission.
2. An error occured while marking your code. The error should be addressed by a maintainer eventually. The error is: ```File extension .bat is not supported```.
3. These submissions must be checked manually because of the potential complexity of submissions, if you've reached this point in the process you're most likely a valid submission.

Please be patient until a maintainer has time to look over your contribution.

***This is an automated response, beep boop.
if you think there is a mistake, contact a maintainer***
> 1f069bc4bc91a1edfb321a5963cd88a9d7f8b0f4

**Comment by RaidAndFade** [comment]
thank you for your improved version.

**Pull request merged**
