### PR TITLE
Yes in java

### PR DESCRIPTION
**Pull request by soulspark666**

### CODE REVIEW

**Comment by RaidAndFade** [comment]
Your pull request seems good, but must be checked by a human maintainer for the following reason(s):
1. Modifications to contributors.md must be checked manually, thanks for your submission.
2. An error occured while marking your code. The error should be addressed by a maintainer eventually. The error is: ```Failed to parse your filename from the code. Please make sure your code is valid!```.
3. These submissions must be checked manually because of the potential complexity of submissions, if you've reached this point in the process you're most likely a valid submission.

Please be patient until a maintainer has time to look over your contribution.

***This is an automated response, beep boop.
if you think there is a mistake, contact a maintainer***
> 58afc0327c32d571407149e0c2fc24896b1516a3

**Comment by RaidAndFade** [comment]
Thank you for revealing a bug in my auto-auditor. 

If you could please change your class name from `Main` to `Yes`, as to conform with Java standards, then I will be happy to merge.

**Comment by soulspark666** [comment]
Changed `Main` to `Yes`!

**Comment by RaidAndFade** [comment]
Awesome! Thank you for participating! Happy hacking!

**Pull request merged**
