### PR TITLE
Add yes.cpp and update contributors.md

### PR DESCRIPTION
**Pull request by GiorgiBeriashvili**
Implement the challenge's solution in C++ programming language.

### CODE REVIEW

**Comment by GiorgiBeriashvili** [comment]
I edited the pull request to submit the C++ implementation since #8 has already submitted for C programming language.

**Comment by RaidAndFade** [comment]
Your pull request seems good, but must be checked by a human maintainer for the following reason(s):
1. Modifications to contributors.md must be checked manually, thanks for your submission.
2. These submissions must be checked manually because of the potential complexity of submissions, if you've reached this point in the process you're most likely a valid submission.

Please be patient until a maintainer has time to look over your contribution.

***This is an automated response, beep boop.
if you think there is a mistake, contact a maintainer***
> a740cfbdd61ef87a25a2fbae68ad7deb06e7f0a8

**Comment by RaidAndFade** [comment]
Thanks for participating! 😄

**Comment by RaidAndFade** [comment]
🤦‍♂ it didn't merge properly because of the conflict and i closed it before i realized that. can you PR again so i can accept it properly this time.

**Pull request closed without merging**
