### PR TITLE
Update contributors.md

### PR DESCRIPTION
**Pull request by joelibaceta**
I'm in

### CODE REVIEW

**Comment by NCPlayz** [comment]
You need to contribute first to be able to get your name on there.

**Comment by joelibaceta** [comment]
:o sorry don't worry, I'm going to find a good issue to contribute :D

**Comment by RaidAndFade** [comment]
😞 @NCPlayz calm down man

**Comment by RaidAndFade** [comment]
Your pull request seems good, but must be checked by a human maintainer for the following reason(s):
1. Modifications to contributors.md must be checked manually, thanks for your submission.

Please be patient until a maintainer has time to look over your contribution.

***This is an automated response, beep boop.
if you think there is a mistake, contact a maintainer***
> 02fea42a33ee0f9e0dd04951cb6d8260f5381b16

**Comment by RaidAndFade** [comment]
Thank you for participating! Make sure to do some challenges as they come out!

**Pull request merged**
