### PR TITLE
print yes using java

### PR DESCRIPTION
**Pull request by zeetec20**

### CODE REVIEW

**Comment by zeetec20** [comment]
hackoctofest

**Comment by RaidAndFade** [comment]
Your pull request needs further work because of the following reason(s):
1. More than one file has been added/removed/modified.

Once you have resolved the issues, **comment on this request to be re-judged**

***This is an automated response, beep boop.
if you think there is a mistake, contact a maintainer***
> 272079d7e54da47e5c55de7451ebe7926ae6abd8

**Comment by RaidAndFade** [comment]
Any specific reason you chmod the entire project...? Also java is already taken.

**Comment by zeetec20** [comment]
hmm no

**Comment by zeetec20** [comment]
i am using linux and, logged in user not super user

**Comment by zeetec20** [comment]
if not chmod project, i cant edit this project

**Comment by RaidAndFade** [comment]
I am also on linux, I did not need to do that. Please check your environment.

**Pull request closed without merging**
