### PR TITLE
Created the "Yes" program in MIPS Assembly

### PR DESCRIPTION
**Pull request by its-kos**
Added my name in the Contributors list and added the Assembly version of the program.

### CODE REVIEW

**Comment by RaidAndFade** [comment]
Your pull request needs further work because of the following reason(s):
1. Your code prints 10 lines that are not yes, such as 
```main.asm:1: error: label or instruction expected at start of line
main.asm:3: warning: label alone on a line without a colon might be in error [-w+orphan-labels]
main.asm:3: error: attempt to define a local label before any non-local labels
```


Once you have resolved the issues, **comment on this request to be re-judged**

***This is an automated response, beep boop.
if you think there is a mistake, contact a maintainer***
> 851990cd7b89a52a5cec7040f9b7963823899dfd

**Comment by its-kos** [comment]
How did you try to compile the program, cause i cant get it to produce that error

**Comment by its-kos** [comment]
This assembles and runs successfully on both QtSpim and Mars

**Comment by RaidAndFade** [comment]
Your pull request needs further work because of the following reason(s):
1. Your code prints 9 lines that are not yes, such as 
```By: its-kos - https://github.com/its-kos:2: warning: label alone on a line without a colon might be in error [-w+orphan-labels]
By: its-kos - https://github.com/its-kos:2: error: attempt to define a local label before any non-local labels
By: its-kos - https://github.com/its-kos:3: error: parser: instruction expected
```


Once you have resolved the issues, **comment on this request to be re-judged**

***This is an automated response, beep boop.
if you think there is a mistake, contact a maintainer***
> d80fa3de93ffbe40b110e0327467ebce91ba475a

**Comment by its-kos** [comment]
> Your pull request needs further work because of the following reason(s):
> 
> 1. Your code prints 9 lines that are not yes, such as
> 
> ```
> By: its-kos - https://github.com/its-kos:2: error: attempt to define a local label before any non-local labels
> By: its-kos - https://github.com/its-kos:3: error: parser: instruction expected
> ```
> 
> Once you have resolved the issues, **comment on this request to be re-judged**
> 
> _**This is an automated response, beep boop. if you think there is a mistake, contact a maintainer**_
> 
> > [d80fa3d](https://github.com/RaidAndFade/OctoberChallenges2019/commit/d80fa3de93ffbe40b110e0327467ebce91ba475a)

What exactly are u assembling this on ? @RaidAndFade

**Comment by its-kos** [comment]
@NCPlayz hey can you review this pull request, cause the automated system finds errors and i dont know how it tries to assemble the code. The last commit works on both QtSpim and Mars.

**Comment by RaidAndFade** [comment]
Your pull request needs further work because of the following reason(s):
1. Your code prints 4 lines that are not yes, such as 
```By: its-kos - https://github.com/its-kos:4: error: parser: instruction expected
By: its-kos - https://github.com/its-kos:7: error: parser: instruction expected
By: its-kos - https://github.com/its-kos:10: error: parser: instruction expected
```


Once you have resolved the issues, **comment on this request to be re-judged**

***This is an automated response, beep boop.
if you think there is a mistake, contact a maintainer***
> 3a193419099ac208ef61a74ccc05f2e9b9d3d54c

**Comment by RaidAndFade** [comment]
The parser runs anything ending with `.asm` on nasm, is there any specific file extension specifically for mips?

**Comment by its-kos** [comment]
I dont think there is, but if you run this on Mars or QtSpim which are for MIPS assembly its runs great

**Comment by RaidAndFade** [comment]
Can you change your extension to `.masm` for me, `.asm` is reserved for x86_64 in this repo.

**Comment by its-kos** [comment]
Done

**Comment by RaidAndFade** [comment]
Awesome, thanks for your contribution.

**Pull request merged**
