### PR TITLE
Yes.py

### PR DESCRIPTION
**Pull request by gargprince1702**
In which code I use While loop with True condition that print "YES" , to stop press CTRL + C

### CODE REVIEW

**Comment by RaidAndFade** [comment]
Your pull request needs further work because of the following reason(s):
1. Your file is not in a project folder ("Yes"). This may be intentional, but most likely not. If it is intentional please tag a maintainer.

Once you have resolved the issues, **comment on this request to be re-judged**

***This is an automated response, beep boop.
if you think there is a mistake, contact a maintainer***
> 82c148c13f3ee950f09450b54de4fb5c22fde69c

**Comment by gargprince1702** [comment]
which things I need to modify in my PR, can you tell?

**Comment by gargprince1702** [comment]
> Your pull request needs further work because of the following reason(s):
> 
> 1. Your file is not in a project folder ("Yes"). This may be intentional, but most likely not. If it is intentional please tag a maintainer.
> 
> Once you have resolved the issues, **comment on this request to be re-judged**
> 
> _**This is an automated response, beep boop. if you think there is a mistake, contact a maintainer**_
> 
> > [82c148c](https://github.com/RaidAndFade/Hacktoberfest2019/commit/82c148c13f3ee950f09450b54de4fb5c22fde69c)

**Comment by RaidAndFade** [comment]
Your pull request needs further work because of the following reason(s):
1. Your file is not in a project folder ("Yes"). This may be intentional, but most likely not. If it is intentional please tag a maintainer.

Once you have resolved the issues, **comment on this request to be re-judged**

***This is an automated response, beep boop.
if you think there is a mistake, contact a maintainer***
> 49549fdaf2a7ac40ca13743d4f364da20852298f

**Comment by gargprince1702** [comment]
How Can make my PR in a project folder

**Comment by RaidAndFade** [comment]
Read the instructions in more detail, everything is explained in the README.

**Pull request closed without merging**
