### PR TITLE
#hacktoberfest!

### PR DESCRIPTION
**Pull request by dovy**
Hope this is how you want it.

### CODE REVIEW

**Comment by dovy** [comment]
Please assign and add a label.  :)

**Comment by RaidAndFade** [comment]
Your pull request seems good, but must be checked by a human maintainer for the following reason(s):
1. Modifications to contributors.md must be checked manually, thanks for your submission.

Please be patient until a maintainer has time to look over your contribution.

***This is an automated response, beep boop.
if you think there is a mistake, contact a maintainer***
> 777a2bd952ef119583ca31db5bfbb41d081b4111

**Comment by NCPlayz** [comment]
Hey! Sorry. We've made a change in policy and no longer accept PRs wishing to simply add their name to the list. You must complete the challenge now, so that we all have fun in doing it! For now, It'll be invalid, but if you wish to complete this week's challenge and add it to the PR, we will accept it and remove the invalid label. Hope you understand!

Hopefully the automated response for contributor-list-only PRs are fixed soon.

**Comment by dovy** [comment]
@NCPlayz I'm confused, the ticket said to just add yourself as the challenge. hah...

**Comment by dovy** [comment]
You should close #1 then, lol.

**Pull request closed without merging**
