### PR TITLE
Added Yes in Go Lang.

### PR DESCRIPTION
**Pull request by PJijin**

### CODE REVIEW

**Comment by RaidAndFade** [comment]
Your pull request needs further work because of the following reason(s):
1. Your code is too slow! It should be printing infinitely many `yes` strings repeatedly in a loop, you only printed 0 in 5 seconds!

Once you have resolved the issues, **comment on this request to be re-judged**

***This is an automated response, beep boop.
if you think there is a mistake, contact a maintainer***
> bdf83a491783dd76b7e607a8f1749f8177530dd4

**Comment by PJijin** [comment]
Updated yes.go

**Comment by RaidAndFade** [comment]
Your pull request needs further work because of the following reason(s):
1. Your code prints 43741 lines that are not yes, such as ```Yes 
Yes 
Yes 
```!


Once you have resolved the issues, **comment on this request to be re-judged**

***This is an automated response, beep boop.
if you think there is a mistake, contact a maintainer***
> 8526667414fb2bc1d77fdb08cd695910b0594260

**Comment by PJijin** [comment]
Updated.

**Comment by RaidAndFade** [comment]
Your pull request seems good, but must be checked by a human maintainer for the following reason(s):
1. These submissions must be checked manually because of the potential complexity of submissions, if you've reached this point in the process you're most likely a valid submission.

Please be patient until a maintainer has time to look over your contribution.

***This is an automated response, beep boop.
if you think there is a mistake, contact a maintainer***
> b3e51f0b6873249bd528553dfef69e9f7756e6e4

**Comment by RaidAndFade** [comment]
Thank you for your contribution! 😄

**Pull request merged**
